export { registerPage } from './signup'
export { authPage } from './signin'
export { changePassword } from './changePassword'
export { changeProfilePage } from './changeProfile'
export { profilePage } from './profile'
export { chatPage } from './chart'
export { page404 } from './error_404'
export { page500 } from './error_500'
